require cmdliner >= 1.0.0
On my machine with cmdliner 0.9.8, `make` fails with

    File "src/opamEdMain.ml", line 185, characters 4-12:
    Error: Unbound value Arg.conv